site_name: "A Simple Standard for Sharing Ontology Mappings (SSSOM)"
theme:
  name: material
  analytics:
    gtag: G-2SYBSJVZ23
#  palette:
#    scheme: slate
#    primary: cyan
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2
markdown_extensions:
  - pymdownx.highlight:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
  - Home: home.md
  - About SSSOM: about.md
  - Specification: index.md
  - Overview: spec.md
  - FAQ: faq.md
  - Credits: credits.md
  - Contact us: contact.md
  - Resources for contributors:
    - How to contribute?: contributing.md
    - Code of Conduct: code_of_conduct.md
  - Resources for users:
    - Use cases: 
      - Overview: usecases.md
      - How to gradually enrich OMOP mappings with SSSOM: tutorials/omop-mappings.md
    - Workshops: workshops.md
    - Presentations: presentations.md
    - Basic Tutorial: tutorial.md
    - Mapping Justifications: mapping-justifications.md
    - How to use mapping predicates: mapping-predicates.md
    - Set up a mapping registry/commons: mapping-commons.md
    - Overview of Chaining Rules: chaining_rules.md
    - A basic guide for the SSSOM toolkit: toolkit.md
    - 5-Star Entity Mappings - Cheatsheet: 5star-mappings.md
    - Update schema/context and release: update.md
    - Matching tool implementation guide: matching-tool-implementation-guide.md
    - SSSOM profiles: sssom-profiles.md
    - Glossary: glossary.md

site_url: https://mapping-commons.github.io/sssom/
repo_url: https://github.com/mapping-commons/sssom/
edit_uri: "edit/master/src/docs/"
