site_name: "A Simple Standard for Sharing Ontology Mappings (SSSOM)"
theme:
  name: material
  analytics:
    gtag: G-2SYBSJVZ23
#  palette:
#    scheme: slate
#    primary: cyan
  features:
    - content.tabs.link
plugins:
  - search
markdown_extensions:
  - pymdownx.highlight:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
nav:
  - Home: home.md
  - About SSSOM: about.md
  - Specification: index.md
  - Overview: spec.md
  - FAQ: faq.md
  - Credits: credits.md
  - Contact us: contact.md
  - Resources for contributors:
    - How to contribute?: contributing.md
    - Code of Conduct: code_of_conduct.md
  - Resources for users:
    - Use cases: usecases.md
    - Workshops: workshops.md
    - Presentations: presentations.md
    - Basic Tutorial: tutorial.md
    - How to use mapping predicates: mapping-predicates.md
    - A basic guide for the SSSOM toolkit: toolkit.md

site_url: https://mapping-commons.github.io/sssom/
repo_url: https://github.com/mapping-commons/sssom/
edit_uri: "edit/master/sssom_schema/src/docs/"
